modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="extraquests"
version="1.0.1"
displayName="ExtraQuests"
logoFile ="logo.png"
authors="Vecoo"
description="Addition to FTB Quests"

[[dependencies.extraquests]]
modId="forge"
mandatory=true
versionRange="[47.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.extraquests]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.extraquests]]
modId="ftbquests"
mandatory=true
versionRange="[2001,)"
ordering="NONE"
side="BOTH"