plugins {
    id 'net.minecraftforge.gradle' version '[7.0.17,8.0)'
    id 'net.minecraftforge.renamer' version '1.0.14'
    id 'com.modrinth.minotaur' version '2.9.0'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

version = "${project_version}-1.12.2-Forge"

minecraft {
    mappings channel: 'stable', version: '39-1.12'
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    compileOnly minecraft.dependency("net.minecraftforge:forge:1.12.2-${forge_12}")

    compileOnly "curse.maven:ftb-quests-forge-289412:${ftbquests_12}"
    compileOnly "curse.maven:ftb-library-legacy-237167:${ftblibrary_12}"
    compileOnly "maven.modrinth:extralib:${extralib}-forge,1.12.2"
}

renamer.classes('renameJarToSrg', tasks.named('jar', Jar)) {
    mappings(minecraft.dependency.toSrg.get())
    output = layout.buildDirectory.file("libs/${rootProject.name}-${project.version}.jar").get().asFile
}

processResources {
    filesMatching('mcmod.info') {
        expand(
                'project_name': project_name,
                'project_version': project_version
        )
    }
}

def gradleProperties = new Properties()
def gradlePropertiesFile = new File(rootProject.file("/.gradle/gradle.properties").path)

if (gradlePropertiesFile.exists()) {
    gradlePropertiesFile.withInputStream { gradleProperties.load(it) }
}

modrinth {
    token = gradleProperties.getProperty("MODRINTH_API_KEY")
    projectId = "extraquests"
    versionName = "${project_name}-${version}"
    versionNumber = project_version
    versionType = "release"
    changelog = rootProject.file("changelog.md").text
    uploadFile = jar
    gameVersions = ["1.12.2"]
    loaders = ["forge"]
    dependencies {
        required.project "extralib"
    }
}

build.finalizedBy('versionedRelease')