org.gradle.jvmargs = -Xmx2g
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.daemon = true

project_name = ExtraQuests
project_version = 1.7.0

forge_12 = 14.23.5.2860
ftbquests_12 = 3015063
ftblibrary_12 = 2985811

forge_16 = 36.2.42
ftbquests_16 = 4297999
ftbteams_16 = 3535953
ftblibrary_16 = 3553840

forge_19 = 43.4.0
ftbquests_19 = 6130546
ftbteams_19 = 4611938
ftblibrary_19 = 4661834

fabric_api_20 = 0.92.9+1.20.1
ftbquests_fabric_20 = 8078537
ftbteams_fabric_20 = 7499808
ftblibrary_fabric_20 = 8226926

fabric_loader = 0.19.2
extralib = 3.0.6

lombok = 1.18.46