modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"

[[mods]]
modId = "extraquests"
version = "1.5.0"
displayName = "ExtraQuests"
logoFile = "logo.png"
authors = "Vecoo"
description = "Sidemod for FTB Quests. Adds new tasks and rewards."

[[dependencies.extraquests]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extraquests]]
modId = "ftbquests"
mandatory = true
versionRange = "[1605,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.extraquests]]
modId = "extralib"
mandatory = true
versionRange = "[1.5,)"
ordering = "NONE"
side = "SERVER"